#!/usr/bin/env ruby

pkg = File.basename(Dir.pwd)

c = File.readlines('PKGBUILD')

c.delete_if { |x| x =~ /^pkgname/ }
  .find { |x| x =~ /^pkgbase/ }.gsub! /base/, 'name'

c = c.reverse
  .drop_while { |x| x != "package_#{pkg}-headers() {\n" }
  .drop(2)
  .reverse

c.find { |x| x =~ /^package_/ }
  .gsub! "_#{pkg}", ''

File.open('PKGBUILD.aur', 'w') { |f| f.write c.join }
