#!/usr/bin/env ruby

c = File.readlines('PKGBUILD')

c.delete_if { |x| x =~ /^pkgname/ }
  .find { |x| x =~ /^pkgbase/ }.gsub! /base/, 'name'

c = c.reverse
  .drop_while { |x| x != "package_linux-pax-headers() {\n" }
  .drop(2)
  .reverse

c.find { |x| x =~ /^package_/ }
  .gsub! '_linux-pax', ''

File.open('PKGBUILD.aur', 'w') { |f| f.write c.join }
